
POST http://localhost:3000/user
Content-Type: application/json

    {
        "name": "Botelho",
        "username": "eraghost",
        "email": "eraghost@gamil.com",
        "password": "MinhaSenha456"
        
    }

###

GET http://localhost:3000/user  

###

GET http://localhost:3000/user/64c0bf6bea2013eba88b1d41

###

PATCH  http://localhost:3000/user/64bf5fbc009f90d21f9925cb
Content-Type: application/json

    {
        "username": "TheTorres"
    }

###

POST http://localhost:3000/auth
Content-Type: application/json

    {
        "email": "eraghost@gamil.com",
        "password": "MinhaSenha456"
    }

###

GET http://localhost:3000/auth/confirm
Content-Type: application/json
Authorization: Bearer .eyJpZCI6IjY0YzBiZjZiZWEyMDEzZWJhODhiMWQ0MSIsImlhdCI6MTY5MDM1Njg3MiwiZXhwIjoxNjkwMzU2OTIzfQ.kuKOlU46-FLS1EyRlKJNkZykpyQ4Me3G3RC0bzdNWW4

